### ISSUE TITLE
Required LDAP userdata fields

### ISSUE THREAD

**Issue by Arnei** [elan-ev/leihs-ldap-authenticator#63]
In the LDAP part of the configuration, the fields for family and given name must point to fields that actually exist for all LDAP users, otherwise the programm will fail (by trying to access the first element of an array that does not exist). I am not sure whether this is how it supposed to work and if this intuitive for Leihs admins. To me as someone new to Leihs, those just looked like optional metadata fields, so I would suggest adding a comment to the configuration that all specified userdata fields MUST exist for all LDAP users.

**Comment by lkiesow** [comment]
Do you happen to have a stack trace?
Pull request #60 (16a23a7) was supposed to fix that.

**Comment by Arnei** [comment]
Now that you mention it, I can't reproduce the issue anymore. Probably got confused while looking at #62. Will close this for now.
